databases:
  - name: postgres

services:
  - type: web
    name: weather
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false